version: '3.3'

services:
  client:
    restart: always
    ports:
      - $PORT_CLIENT:3000
    build: .
    stdin_open: true
    tty: true
    command: yarn start
    depends_on:
      - web
    environment:
      NODE_ENV: development
      REACT_APP_API_PATH: $URL_API
      REACT_APP_REDIRECT_PATH: $URL_CLIENT/redirect
      REACT_APP_CLIENT_ID: skwIPnbi7N3uIvNysUbi0xfXwnWaIMR1MCJxz8rV0dGxeMJD
      CHOKIDAR_USEPOLLING: 'true'
      MINIO_HOST: localhost
    volumes:
      - .:/usr/src

  db:
    restart: always
    image: postgres

  web:
    image: assemble/foundation
    environment:
      - DATA=postgres://postgres:postgres@db
      - PASSWORD
      - PORT=3000
      - RAILS_ENV=development
    ports:
      - $PORT_API:3000
    volumes:
      - ./db:/foundation/db
      - ./models:/foundation/app/models
    depends_on:
      - db
