version: '3.3'

services:
  selenium:
    image: selenium/standalone-firefox-debug
    depends_on:
      - client
    volumes:
      # The images need access to the hosts' shared memory;
      # see https://github.com/SeleniumHQ/docker-selenium#running-the-images
      - /dev/shm:/dev/shm
    expose:
      - 4444

  spec:
    build: ./spec
    depends_on:
      - selenium
    volumes:
      - ./spec:/spec
    environment:
      - SELENIUM_HOST=selenium
      - TEST_APP_HOST=client
      - TEST_APP_PORT=3000

  client:
    restart: always
    ports:
      - $PORT_CLIENT:3000
    build: .
    stdin_open: true
    tty: true
    command: yarn start
    depends_on:
      - web
    environment:
      NODE_ENV: development
      REACT_APP_API_PATH: $URL_API
      REACT_APP_REDIRECT_PATH: $URL_CLIENT/redirect
      REACT_APP_CPRO_PATH: $URL_CPRO
      REACT_APP_CLIENT_ID: skwIPnbi7N3uIvNysUbi0xfXwnWaIMR1MCJxz8rV0dGxeMJD
      CHOKIDAR_USEPOLLING: 'true'
      MINIO_HOST: localhost
    volumes:
      - .:/usr/src

  web:
    build: ./server
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db
      - PASSWORD
      - PORT=3000
      - RAILS_ENV=development
      - SELENIUM_HOST=selenium
      - TEST_APP_HOST=frontend
      - TEST_APP_PORT=3000
    ports:
      - $PORT_API:3000
    volumes:
      - ./server:/app
      - frontend
    depends_on:
      - db
    working_dir: /app
    networks:
      - tbapi

  db:
    restart: always
    image: postgres
    networks:
      - tbapi

  minio1:
    image: minio/minio:RELEASE.2018-11-06T01-01-02Z
    volumes:
      - data1:/data
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data

  minio2:
    image: minio/minio:RELEASE.2018-11-06T01-01-02Z
    volumes:
      - data2:/data
    ports:
      - "9002:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data

  minio3:
    image: minio/minio:RELEASE.2018-11-06T01-01-02Z
    volumes:
      - data3:/data
    ports:
      - "9003:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data

  minio4:
    image: minio/minio:RELEASE.2018-11-06T01-01-02Z
    volumes:
      - data4:/data
    ports:
      - "9004:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data

volumes:
  data1:
  data2:
  data3:
  data4:

networks:
  tbapi:
