default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV['DATA'] %>/development

test:
  <<: *default
  url: <%= ENV['DATA'] %>/test

production:
  <<: *default
  url: <%= ENV['DATA'] %>/production
